// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Marina Rocha Lhamby"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tickets": {
            "get": {
                "description": "Fetch total number of tickets by period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Fetch total number of tickets by period",
                "parameters": [
                    {
                        "type": "string",
                        "description": "início da manhã, manhã, tarde ou noite",
                        "name": "period",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.TotalTicketsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tickets/destination/average/{destination}": {
            "get": {
                "description": "Fetch average number of tickets by destination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Fetch average number of tickets by destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination",
                        "name": "destination",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.AverageTicketsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/tickets/destination/{destination}": {
            "get": {
                "description": "Fetch number of tickets by destination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Fetch number of tickets by destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination",
                        "name": "destination",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.TotalTicketsResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AverageTicketsResponse": {
            "type": "object",
            "properties": {
                "average": {
                    "type": "number"
                }
            }
        },
        "domain.TotalTicketsResponse": {
            "type": "object",
            "properties": {
                "totalTickets": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Desafio Go Web Docs",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
